### ISSUE TITLE
invalid non-responsive link for DHTXXD.zip in install.sh

### ISSUE THREAD

**Issue by ptegler** [rcrum003/HiveControl#60] opened 2019-07-03 23:40 UTC

**Comment by ptegler** [comment] 2019-07-03 23:42
bold text link below never connected twice
offline testing did find a responsive link at
http://abyz.me.uk/rpi/pigpio/code/DHTXXD.zip
while 
http://abyz.co.uk/rpi/pigpio/code/DHTXXD.zip*
never responded and hung script

#Installing DHTXX Code
	echo "Installing DHT Code"
	cd /home/HiveControl/software
	sudo mkdir DHTXXD
	cd DHTXXD
	sudo wget **http://abyz.co.uk/rpi/pigpio/code/DHTXXD.zip**
	unzip DHTXXD.zip
	sudo gcc -Wall -pthread -o DHTXXD test_DHTXXD.c DHTXXD.c -lpigpiod_if2
	sudo cp DHTXXD /usr/local/bin/

**Comment by rcrum003** [comment] 2019-07-04 01:01
I’ll take a look and see what the problem is.

**Comment by rcrum003** [comment] 2019-07-04 01:51
Now fixed in version 44 of the Install.sh script - please re-download the full GIT project

**Closed as completed by rcrum003** 2019-07-04 01:51 UTC
